#define MAXIMUM_BUFFER_SIZE 128

#define ENABLE 1
#define DISABLE 0
#define CW 1
#define CCW 0

#define PWR_CREATER_BUFFER_SIZE 64
#define MOTOR_COUNTS (ENABLE_V1 + ENABLE_V2 + ENABLE_V3 + ENABLE_V4 + ENABLE_V5 + ENABLE_V6 + ENABLE_V7 + ENABLE_V8)

#define BUTTON_PRESS true
#define BUTTON_RELEASE false